name: Cats vs Dogs CI/CD Pipeline

on:
  push:
    branches: [ main, devop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/dev.txt
    
    - name: Create test database
      run: |
        python -c "from database.models import create_tables; create_tables()"
    
    - name: Run tests
      run: |
        pytest tests/ -v --junitxml=test-results.xml --cov=src --cov-report=xml
    
    - name: Run performance tests
      run: |
        pytest tests/test_performance.py -v --junitxml=performance-results.xml
        
    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: test-results.xml
      if: always()

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    
    - name: Run linting
      run: |
        flake8 src/ tests/

  deploy:
    needs: [test, lint]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Build and push Docker image
      run: |
        echo "Docker build and push would go here"
      # Uncomment and configure when ready for deployment
      # - uses: docker/build-push-action@v2
      #   with:
      #     push: true
      #     tags: your-registry/cats-vs-dogs:latest